 Pokemon Moves
 number, name, catagory, power, accuracy, type
insert into moves values(1, 'Pound', 'Physical', 40, 100, 'Normal')
insert into moves values(2, 'Karate Chop', 'Physical', 50, 100, 'Fighting')
insert into moves values(3, 'Double Slap', 'Physical', 15, 85, 'Normal')
insert into moves values(4, 'Comet Punch', 'Physical', 18, 85, 'Normal')
insert into moves values(5, 'Mega Punch', 'Physical', 80, 85, 'Normal')
insert into moves values(6, 'Pay Day', 'Physical', 40, 100, 'Normal')
insert into moves values(7, 'Fire Punch', 'Physical', 75, 100, 'Fire')
insert into moves values(8, 'Ice Punch', 'Physical', 75, 100, 'Ice')
insert into moves values(9, 'Thunder Punch', 'Physical', 75, 100, 'Electric')
insert into moves values(10, 'Scratch', 'Physical', 40, 100, 'Normal')
insert into moves values(11, 'Vice Grip', 'Physical', 55, 100, 'Normal')
insert into moves values(12, 'Guillotine', 'Physical', NULL, NULL, 'Normal')
insert into moves values(13, 'Razor Wind', 'Special', 80, 100, 'Normal')
insert into moves values(14, 'Swords Dance', 'Status', NULL, NULL, 'Normal')
insert into moves values(15, 'Cut', 'Physical', 50, 95, 'Normal')
insert into moves values(16, 'Gust', 'Special', 40, 100, 'Flying')
insert into moves values(17, 'Wing Attack', 'Physical', 60, 100, 'Flying')
insert into moves values(18, 'Whirlwind', 'Status', NULL, NULL, 'Normal')
insert into moves values(19, 'Fly', 'Physical', 90, 95, 'Flying')
insert into moves values(20, 'Bind', 'Physical', 15, 85, 'Normal')
insert into moves values(21, 'Slam', 'Physical', 80, 75, 'Normal')
insert into moves values(22, 'Vine Whip', 'Physical', 45, 100, 'Grass')
insert into moves values(23, 'Stomp', 'Physical', 65, 100, 'Normal')
insert into moves values(24, 'Double Kick', 'Physical', 30, 100, 'Fighting')
insert into moves values(25, 'Mega Kick', 'Physical', 120, 75, 'Normal')
insert into moves values(26, 'Jump Kick', 'Physical', 100, 95, 'Fighting')
insert into moves values(27, 'Rolling Kick', 'Physical', 60, 85, 'Fighting')
insert into moves values(28, 'Sand Attack', 'Status', NULL, 100, 'Ground')
insert into moves values(29, 'Headbutt', 'Physical', 70, 100, 'Normal')
insert into moves values(30, 'Horn Attack', 'Physical', 65, 100, 'Normal')
insert into moves values(31, 'Fury Attack', 'Physical', 15, 85, 'Normal')
insert into moves values(32, 'Horn Drill', 'Physical', NULL, NULL, 'Normal')
insert into moves values(33, 'Tackle', 'Physical', 50, 100, 'Normal')
insert into moves values(34, 'Body Slam', 'Physical', 85, 100, 'Normal')
insert into moves values(35, 'Wrap', 'Physical', 15, 90, 'Normal')
insert into moves values(36, 'Take Down', 'Physical', 90, 85, 'Normal')
insert into moves values(37, 'Thrash', 'Physical', 120, 100, 'Normal')
insert into moves values(38, 'Double-Edge', 'Physical', 120, 100, 'Normal')
insert into moves values(39, 'Tail Whip', 'Status', NULL, 100, 'Normal')
insert into moves values(40, 'Poison Sting', 'Physical', 15, 100, 'Poison')
insert into moves values(41, 'Twineedle', 'Physical', 25, 100, 'Bug')
insert into moves values(42, 'Pin Missile', 'Physical', 25, 95, 'Bug')
insert into moves values(43, 'Leer', 'Status', NULL, 100, 'Normal')
insert into moves values(44, 'Bite', 'Physical', 60, 100, 'Dark')
insert into moves values(45, 'Growl', 'Status', NULL, 100, 'Normal')
insert into moves values(46, 'Roar', 'Status', NULL, NULL, 'Normal')
insert into moves values(47, 'Sing', 'Status', NULL, 55, 'Normal')
insert into moves values(48, 'Supersonic', 'Status', NULL, 55, 'Normal')
insert into moves values(49, 'Sonic Boom', 'Special', , 90, 'Normal')
insert into moves values(50, 'Disable', 'Status', NULL, 100, 'Normal')
insert into moves values(51, 'Acid', 'Special', 40, 100, 'Poison')
insert into moves values(52, 'Ember', 'Special', 40, 100, 'Fire')
insert into moves values(53, 'Flamethrower', 'Special', 90, 100, 'Fire')
insert into moves values(54, 'Mist', 'Status', NULL, NULL, 'Ice')
insert into moves values(55, 'Water Gun', 'Special', 40, 100, 'Water')
insert into moves values(56, 'Hydro Pump', 'Special', 110, 80, 'Water')
insert into moves values(57, 'Surf', 'Special', 90, 100, 'Water')
insert into moves values(58, 'Ice Beam', 'Special', 90, 100, 'Ice')
insert into moves values(59, 'Blizzard', 'Special', 110, 70, 'Ice')
insert into moves values(60, 'Psybeam', 'Special', 65, 100, 'Psychic')
insert into moves values(61, 'Bubble Beam', 'Special', 65, 100, 'Water')
insert into moves values(62, 'Aurora Beam', 'Special', 65, 100, 'Ice')
insert into moves values(63, 'Hyper Beam', 'Special', 150, 90, 'Normal')
insert into moves values(64, 'Peck', 'Physical', 35, 100, 'Flying')
insert into moves values(65, 'Drill Peck', 'Physical', 80, 100, 'Flying')
insert into moves values(66, 'Submission', 'Physical', 80, 80, 'Fighting')
insert into moves values(67, 'Low Kick', 'Physical', NULL, 100, 'Fighting')
insert into moves values(68, 'Counter', 'Physical', NULL, 100, 'Fighting')
insert into moves values(69, 'Seismic Toss', 'Physical', NULL, 100, 'Fighting')
insert into moves values(70, 'Strength', 'Physical', 80, 100, 'Normal')
insert into moves values(71, 'Absorb', 'Special', 20, 100, 'Grass')
insert into moves values(72, 'Mega Drain', 'Special', 40, 100, 'Grass')
insert into moves values(73, 'Leech Seed', 'Status', NULL, 90, 'Grass')
insert into moves values(74, 'Growth', 'Status', NULL, NULL, 'Normal')
insert into moves values(75, 'Razor Leaf', 'Physical', 55, 95, 'Grass')
insert into moves values(76, 'Solar Beam', 'Special', 120, 100, 'Grass')
insert into moves values(77, 'Poison Powder', 'Status', NULL, 75, 'Poison')
insert into moves values(78, 'Stun Spore', 'Status', NULL, 75, 'Grass')
insert into moves values(79, 'Sleep Powder', 'Status', NULL, 75, 'Grass')
insert into moves values(80, 'Petal Dance', 'Special', 120, 100, 'Grass')
insert into moves values(81, 'String Shot', 'Status', NULL, 95, 'Bug')
insert into moves values(82, 'Dragon Rage', 'Special', , 100, 'Dragon')
insert into moves values(83, 'Fire Spin', 'Special', 35, 85, 'Fire')
insert into moves values(84, 'Thunder Shock', 'Special', 40, 100, 'Electric')
insert into moves values(85, 'Thunderbolt', 'Special', 90, 100, 'Electric')
insert into moves values(86, 'Thunder Wave', 'Status', NULL, 100, 'Electric')
insert into moves values(87, 'Thunder', 'Special', 110, 70, 'Electric')
insert into moves values(88, 'Rock Throw', 'Physical', 50, 90, 'Rock')
insert into moves values(89, 'Earthquake', 'Physical', 100, 100, 'Ground')
insert into moves values(90, 'Fissure', 'Physical', NULL, NULL, 'Ground')
insert into moves values(91, 'Dig', 'Physical', 80, 100, 'Ground')
insert into moves values(92, 'Toxic', 'Status', NULL, 90, 'Poison')
insert into moves values(93, 'Confusion', 'Special', 50, 100, 'Psychic')
insert into moves values(94, 'Psychic', 'Special', 90, 100, 'Psychic')
insert into moves values(95, 'Hypnosis', 'Status', NULL, 60, 'Psychic')
insert into moves values(96, 'Meditate', 'Status', NULL, NULL, 'Psychic')
insert into moves values(97, 'Agility', 'Status', NULL, NULL, 'Psychic')
insert into moves values(98, 'Quick Attack', 'Physical', 40, 100, 'Normal')
insert into moves values(99, 'Rage', 'Physical', 20, 100, 'Normal')
insert into moves values(100, 'Teleport', 'Status', NULL, NULL, 'Psychic')
insert into moves values(101, 'Night Shade', 'Special', NULL, 100, 'Ghost')
insert into moves values(102, 'Mimic', 'Status', NULL, 100, 'Normal')
insert into moves values(103, 'Screech', 'Status', NULL, 85, 'Normal')
insert into moves values(104, 'Double Team', 'Status', NULL, NULL, 'Normal')
insert into moves values(105, 'Recover', 'Status', NULL, NULL, 'Normal')
insert into moves values(106, 'Harden', 'Status', NULL, NULL, 'Normal')
insert into moves values(107, 'Minimize', 'Status', NULL, NULL, 'Normal')
insert into moves values(108, 'Smokescreen', 'Status', NULL, 100, 'Normal')
insert into moves values(109, 'Confuse Ray', 'Status', NULL, 100, 'Ghost')
insert into moves values(110, 'Withdraw', 'Status', NULL, NULL, 'Water')
insert into moves values(111, 'Defense Curl', 'Status', NULL, NULL, 'Normal')
insert into moves values(112, 'Barrier', 'Status', NULL, NULL, 'Psychic')
insert into moves values(113, 'Light Screen', 'Status', NULL, NULL, 'Psychic')
insert into moves values(114, 'Haze', 'Status', NULL, NULL, 'Ice')
insert into moves values(115, 'Reflect', 'Status', NULL, NULL, 'Psychic')
insert into moves values(116, 'Focus Energy', 'Status', NULL, NULL, 'Normal')
insert into moves values(117, 'Bide', 'Physical', NULL, 100, 'Normal')
insert into moves values(118, 'Metronome', 'Status', NULL, NULL, 'Normal')
insert into moves values(119, 'Mirror Move', 'Status', NULL, NULL, 'Flying')
insert into moves values(120, 'Self-Destruct', 'Physical', 200, 100, 'Normal')
insert into moves values(121, 'Egg Bomb', 'Physical', 100, 75, 'Normal')
insert into moves values(122, 'Lick', 'Physical', 30, 100, 'Ghost')
insert into moves values(123, 'Smog', 'Special', 30, 70, 'Poison')
insert into moves values(124, 'Sludge', 'Special', 65, 100, 'Poison')
insert into moves values(125, 'Bone Club', 'Physical', 65, 85, 'Ground')
insert into moves values(126, 'Fire Blast', 'Special', 110, 85, 'Fire')
insert into moves values(127, 'Waterfall', 'Physical', 80, 100, 'Water')
insert into moves values(128, 'Clamp', 'Physical', 35, 85, 'Water')
insert into moves values(129, 'Swift', 'Special', 60, NULL, 'Normal')
insert into moves values(130, 'Skull Bash', 'Physical', 130, 100, 'Normal')
insert into moves values(131, 'Spike Cannon', 'Physical', 20, 100, 'Normal')
insert into moves values(132, 'Constrict', 'Physical', 10, 100, 'Normal')
insert into moves values(133, 'Amnesia', 'Status', NULL, NULL, 'Psychic')
insert into moves values(134, 'Kinesis', 'Status', NULL, 80, 'Psychic')
insert into moves values(135, 'Soft-Boiled', 'Status', NULL, NULL, 'Normal')
insert into moves values(136, 'High Jump Kick', 'Physical', 10, 130, 'Fighting')
insert into moves values(137, 'Glare', 'Status', NULL, 100, 'Normal')
insert into moves values(138, 'Dream Eater', 'Special', 100, 100, 'Psychic')
insert into moves values(139, 'Poison Gas', 'Status', NULL, 90, 'Poison')
insert into moves values(140, 'Barrage', 'Physical', 15, 85, 'Normal')
insert into moves values(141, 'Leech Life', 'Physical', 20, 100, 'Bug')
insert into moves values(142, 'Lovely Kiss', 'Status', NULL, 75, 'Normal')
insert into moves values(143, 'Sky Attack', 'Physical', 140, 90, 'Flying')
insert into moves values(144, 'Transform', 'Status', NULL, NULL, 'Normal')
insert into moves values(145, 'Bubble', 'Special', 40, 100, 'Water')
insert into moves values(146, 'Dizzy Punch', 'Physical', 70, 100, 'Normal')
insert into moves values(147, 'Spore', 'Status', NULL, 100, 'Grass')
insert into moves values(148, 'Flash', 'Status', NULL, 100, 'Normal')
insert into moves values(149, 'Psywave', 'Special', NULL, 100, 'Psychic')
insert into moves values(150, 'Splash', 'Status', NULL, NULL, 'Normal')
insert into moves values(151, 'Acid Armor', 'Status', NULL, NULL, 'Poison')
insert into moves values(152, 'Crabhammer', 'Physical', 100, 90, 'Water')
insert into moves values(153, 'Explosion', 'Physical', 250, 100, 'Normal')
insert into moves values(154, 'Fury Swipes', 'Physical', 18, 80, 'Normal')
insert into moves values(155, 'Bonemerang', 'Physical', 50, 90, 'Ground')
insert into moves values(156, 'Rest', 'Status', NULL, NULL, 'Psychic')
insert into moves values(157, 'Rock Slide', 'Physical', 75, 90, 'Rock')
insert into moves values(158, 'Hyper Fang', 'Physical', 80, 90, 'Normal')
insert into moves values(159, 'Sharpen', 'Status', NULL, NULL, 'Normal')
insert into moves values(160, 'Conversion', 'Status', NULL, NULL, 'Normal')
insert into moves values(161, 'Tri Attack', 'Special', 80, 100, 'Normal')
insert into moves values(162, 'Super Fang', 'Physical', NULL, 90, 'Normal')
insert into moves values(163, 'Slash', 'Physical', 70, 100, 'Normal')
insert into moves values(164, 'Substitute', 'Status', NULL, NULL, 'Normal')
insert into moves values(165, 'Struggle', 'Physical', 50, 100, 'Normal')
insert into moves values(166, 'Sketch', 'Status', NULL, NULL, 'Normal')
insert into moves values(167, 'Triple Kick', 'Physical', 10, 90, 'Fighting')
insert into moves values(168, 'Thief', 'Physical', 60, 100, 'Dark')
insert into moves values(169, 'Spider Web', 'Status', NULL, 100, 'Bug')
insert into moves values(170, 'Mind Reader', 'Status', NULL, 100, 'Normal')
insert into moves values(171, 'Nightmare', 'Status', NULL, 100, 'Ghost')
insert into moves values(172, 'Flame Wheel', 'Physical', 60, 100, 'Fire')
insert into moves values(173, 'Snore', 'Special', 50, 100, 'Normal')
insert into moves values(174, 'Curse', 'Status', NULL, NULL, 'Ghost')
insert into moves values(175, 'Flail', 'Physical', NULL, 100, 'Normal')
insert into moves values(176, 'Conversion 2', 'Status', NULL, 100, 'Normal')
insert into moves values(177, 'Aeroblast', 'Special', 100, 95, 'Flying')
insert into moves values(178, 'Cotton Spore', 'Status', NULL, 100, 'Grass')
insert into moves values(179, 'Reversal', 'Physical', NULL, 100, 'Fighting')
insert into moves values(180, 'Spite', 'Status', NULL, 100, 'Ghost')
insert into moves values(181, 'Powder Snow', 'Special', 40, 100, 'Ice')
insert into moves values(182, 'Protect', 'Status', NULL, NULL, 'Normal')
insert into moves values(183, 'Mach Punch', 'Physical', 40, 100, 'Fighting')
insert into moves values(184, 'Scary Face', 'Status', NULL, 100, 'Normal')
insert into moves values(185, 'Feint Attack', 'Physical', 60, NULL, 'Dark')
insert into moves values(186, 'Sweet Kiss', 'Status', NULL, 75, 'Fairy')
insert into moves values(187, 'Belly Drum', 'Status', NULL, NULL, 'Normal')
insert into moves values(188, 'Sludge Bomb', 'Special', 90, 100, 'Poison')
insert into moves values(189, 'Mud-Slap', 'Special', 20, 100, 'Ground')
insert into moves values(190, 'Octazooka', 'Special', 65, 85, 'Water')
insert into moves values(191, 'Spikes', 'Status', NULL, NULL, 'Ground')
insert into moves values(192, 'Zap Cannon', 'Special', 120, 50, 'Electric')
insert into moves values(193, 'Foresight', 'Status', NULL, 100, 'Normal')
insert into moves values(194, 'Destiny Bond', 'Status', NULL, NULL, 'Ghost')
insert into moves values(195, 'Perish Song', 'Status', NULL, NULL, 'Normal')
insert into moves values(196, 'Icy Wind', 'Special', 55, 95, 'Ice')
insert into moves values(197, 'Detect', 'Status', NULL, NULL, 'Fighting')
insert into moves values(198, 'Bone Rush', 'Physical', 25, 90, 'Ground')
insert into moves values(199, 'Lock-On', 'Status', NULL, 100, 'Normal')
insert into moves values(200, 'Outrage', 'Physical', 120, 100, 'Dragon')
insert into moves values(201, 'Sandstorm', 'Status', NULL, NULL, 'Rock')
insert into moves values(202, 'Giga Drain', 'Special', 75, 100, 'Grass')
insert into moves values(203, 'Endure', 'Status', NULL, NULL, 'Normal')
insert into moves values(204, 'Charm', 'Status', NULL, 100, 'Fairy')
insert into moves values(205, 'Rollout', 'Physical', 30, 90, 'Rock')
insert into moves values(206, 'False Swipe', 'Physical', 40, 100, 'Normal')
insert into moves values(207, 'Swagger', 'Status', NULL, 90, 'Normal')
insert into moves values(208, 'Milk Drink', 'Status', NULL, NULL, 'Normal')
insert into moves values(209, 'Spark', 'Physical', 65, 100, 'Electric')
insert into moves values(210, 'Fury Cutter', 'Physical', 40, 95, 'Bug')
insert into moves values(211, 'Steel Wing', 'Physical', 70, 90, 'Steel')
insert into moves values(212, 'Mean Look', 'Status', NULL, 100, 'Normal')
insert into moves values(213, 'Attract', 'Status', NULL, 100, 'Normal')
insert into moves values(214, 'Sleep Talk', 'Status', NULL, NULL, 'Normal')
insert into moves values(215, 'Heal Bell', 'Status', NULL, NULL, 'Normal')
insert into moves values(216, 'Return', 'Physical', NULL, 100, 'Normal')
insert into moves values(217, 'Present', 'Physical', NULL, 90, 'Normal')
insert into moves values(218, 'Frustration', 'Physical', NULL, 100, 'Normal')
insert into moves values(219, 'Safeguard', 'Status', NULL, NULL, 'Normal')
insert into moves values(220, 'Pain Split', 'Status', NULL, 100, 'Normal')
insert into moves values(221, 'Sacred Fire', 'Physical', 100, 95, 'Fire')
insert into moves values(222, 'Magnitude', 'Physical', NULL, 100, 'Ground')
insert into moves values(223, 'Dynamic Punch', 'Physical', 100, 50, 'Fighting')
insert into moves values(224, 'Megahorn', 'Physical', 120, 85, 'Bug')
insert into moves values(225, 'Dragon Breath', 'Special', 60, 100, 'Dragon')
insert into moves values(226, 'Baton Pass', 'Status', NULL, NULL, 'Normal')
insert into moves values(227, 'Encore', 'Status', NULL, 100, 'Normal')
insert into moves values(228, 'Pursuit', 'Physical', 40, 100, 'Dark')
insert into moves values(229, 'Rapid Spin', 'Physical', 20, 100, 'Normal')
insert into moves values(230, 'Sweet Scent', 'Status', NULL, 100, 'Normal')
insert into moves values(231, 'Iron Tail', 'Physical', 100, 75, 'Steel')
insert into moves values(232, 'Metal Claw', 'Physical', 50, 95, 'Steel')
insert into moves values(233, 'Vital Throw', 'Physical', 70, 100, 'Fighting')
insert into moves values(234, 'Morning Sun', 'Status', NULL, NULL, 'Normal')
insert into moves values(235, 'Synthesis', 'Status', NULL, NULL, 'Grass')
insert into moves values(236, 'Moonlight', 'Status', NULL, NULL, 'Fairy')
insert into moves values(237, 'Hidden Power', 'Special', 60, 100, 'Normal')
insert into moves values(238, 'Cross Chop', 'Physical', 100, 80, 'Fighting')
insert into moves values(239, 'Twister', 'Special', 40, 100, 'Dragon')
insert into moves values(240, 'Rain Dance', 'Status', NULL, NULL, 'Water')
insert into moves values(241, 'Sunny Day', 'Status', NULL, NULL, 'Fire')
insert into moves values(242, 'Crunch', 'Physical', 80, 100, 'Dark')
insert into moves values(243, 'Mirror Coat', 'Special', NULL, 100, 'Psychic')
insert into moves values(244, 'Psych Up', 'Status', NULL, NULL, 'Normal')
insert into moves values(245, 'Extreme Speed', 'Physical', 80, 100, 'Normal')
insert into moves values(246, 'Ancient Power', 'Special', 60, 100, 'Rock')
insert into moves values(247, 'Shadow Ball', 'Special', 80, 100, 'Ghost')
insert into moves values(248, 'Future Sight', 'Special', 120, 100, 'Psychic')
insert into moves values(249, 'Rock Smash', 'Physical', 40, 100, 'Fighting')
insert into moves values(250, 'Whirlpool', 'Special', 35, 85, 'Water')
insert into moves values(251, 'Beat Up', 'Physical', NULL, 100, 'Dark')
insert into moves values(252, 'Fake Out', 'Physical', 40, 100, 'Normal')
insert into moves values(253, 'Uproar', 'Special', 90, 100, 'Normal')
insert into moves values(254, 'Stockpile', 'Status', NULL, NULL, 'Normal')
insert into moves values(255, 'Spit Up', 'Special', NULL, 100, 'Normal')
insert into moves values(256, 'Swallow', 'Status', NULL, NULL, 'Normal')
insert into moves values(257, 'Heat Wave', 'Special', 95, 90, 'Fire')
insert into moves values(258, 'Hail', 'Status', NULL, NULL, 'Ice')
insert into moves values(259, 'Torment', 'Status', NULL, 100, 'Dark')
insert into moves values(260, 'Flatter', 'Status', NULL, 100, 'Dark')
insert into moves values(261, 'Will-O-Wisp', 'Status', NULL, 85, 'Fire')
insert into moves values(262, 'Memento', 'Status', NULL, 100, 'Dark')
insert into moves values(263, 'Facade', 'Physical', 70, 100, 'Normal')
insert into moves values(264, 'Focus Punch', 'Physical', 150, 100, 'Fighting')
insert into moves values(265, 'Smelling Salts', 'Physical', 70, 100, 'Normal')
insert into moves values(266, 'Follow Me', 'Status', NULL, 100, 'Normal')
insert into moves values(267, 'Nature Power', 'Status', NULL, NULL, 'Normal')
insert into moves values(268, 'Charge', 'Status', NULL, NULL, 'Electric')
insert into moves values(269, 'Taunt', 'Status', NULL, 100, 'Dark')
insert into moves values(270, 'Helping Hand', 'Status', NULL, NULL, 'Normal')
insert into moves values(271, 'Trick', 'Status', NULL, 100, 'Psychic')
insert into moves values(272, 'Role Play', 'Status', NULL, NULL, 'Psychic')
insert into moves values(273, 'Wish', 'Status', NULL, NULL, 'Normal')
insert into moves values(274, 'Assist', 'Status', NULL, NULL, 'Normal')
insert into moves values(275, 'Ingrain', 'Status', NULL, NULL, 'Grass')
insert into moves values(276, 'Superpower', 'Physical', 120, 100, 'Fighting')
insert into moves values(277, 'Magic Coat', 'Status', NULL, NULL, 'Psychic')
insert into moves values(278, 'Recycle', 'Status', NULL, 100, 'Normal')
insert into moves values(279, 'Revenge', 'Physical', 60, 100, 'Fighting')
insert into moves values(280, 'Brick Break', 'Physical', 75, 100, 'Fighting')
insert into moves values(281, 'Yawn', 'Status', NULL, 100, 'Normal')
insert into moves values(282, 'Knock Off', 'Physical', 65, 100, 'Dark')
insert into moves values(283, 'Endeavor', 'Physical', NULL, 100, 'Normal')
insert into moves values(284, 'Eruption', 'Special', NULL, 100, 'Fire')
insert into moves values(285, 'Skill Swap', 'Status', NULL, 100, 'Psychic')
insert into moves values(286, 'Imprison', 'Status', NULL, 100, 'Psychic')
insert into moves values(287, 'Refresh', 'Status', NULL, 100, 'Normal')
insert into moves values(288, 'Grudge', 'Status', NULL, 100, 'Ghost')
insert into moves values(289, 'Snatch', 'Status', NULL, 100, 'Dark')
insert into moves values(290, 'Secret Power', 'Physical', 70, 100, 'Normal')
insert into moves values(291, 'Dive', 'Physical', 80, 100, 'Water')
insert into moves values(292, 'Arm Thrust', 'Physical', 15, 100, 'Fighting')
insert into moves values(293, 'Camouflage', 'Status', NULL, 100, 'Normal')
insert into moves values(294, 'Tail Glow', 'Status', NULL, 100, 'Bug')
insert into moves values(295, 'Luster Purge', 'Special', 70, 100, 'Psychic')
insert into moves values(296, 'Mist Ball', 'Special', 70, 100, 'Psychic')
insert into moves values(297, 'Feather Dance', 'Status', NULL, 100, 'Flying')
insert into moves values(298, 'Teeter Dance', 'Status', NULL, 100, 'Normal')
insert into moves values(299, 'Blaze Kick', 'Physical', 85, 90, 'Fire')
insert into moves values(300, 'Mud Sport', 'Status', NULL, 100, 'Ground')
insert into moves values(301, 'Ice Ball', 'Physical', 30, 90, 'Ice')
insert into moves values(302, 'Needle Arm', 'Physical', 60, 100, 'Grass')
insert into moves values(303, 'Slack Off', 'Status', NULL, 100, 'Normal')
insert into moves values(304, 'Hyper Voice', 'Special', 90, 100, 'Normal')
insert into moves values(305, 'Poison Fang', 'Physical', 50, 100, 'Poison')
insert into moves values(306, 'Crush Claw', 'Physical', 75, 95, 'Normal')
insert into moves values(307, 'Blast Burn', 'Special', 150, 90, 'Fire')
insert into moves values(308, 'Hydro Cannon', 'Special', 150, 90, 'Water')
insert into moves values(309, 'Meteor Mash', 'Physical', 90, 90, 'Steel')
insert into moves values(310, 'Astonish', 'Physical', 30, 100, 'Ghost')
insert into moves values(311, 'Weather Ball', 'Special', 50, 100, 'Normal')
insert into moves values(312, 'Aromatherapy', 'Status', NULL, NULL, 'Grass')
insert into moves values(313, 'Fake Tears', 'Status', NULL, 100, 'Dark')
insert into moves values(314, 'Air Cutter', 'Special', 60, 95, 'Flying')
insert into moves values(315, 'Overheat', 'Special', 130, 90, 'Fire')
insert into moves values(316, 'Odor Sleuth', 'Status', NULL, 100, 'Normal')
insert into moves values(317, 'Rock Tomb', 'Physical', 60, 95, 'Rock')
insert into moves values(318, 'Silver Wind', 'Special', 60, 100, 'Bug')
insert into moves values(319, 'Metal Sound', 'Status', NULL, 85, 'Steel')
insert into moves values(320, 'Grass Whistle', 'Status', NULL, 55, 'Grass')
insert into moves values(321, 'Tickle', 'Status', NULL, 100, 'Normal')
insert into moves values(322, 'Cosmic Power', 'Status', NULL, NULL, 'Psychic')
insert into moves values(323, 'Water Spout', 'Special', NULL, 100, 'Water')
insert into moves values(324, 'Signal Beam', 'Special', 75, 100, 'Bug')
insert into moves values(325, 'Shadow Punch', 'Physical', 60, NULL, 'Ghost')
insert into moves values(326, 'Extrasensory', 'Special', 80, 100, 'Psychic')
insert into moves values(327, 'Sky Uppercut', 'Physical', 85, 90, 'Fighting')
insert into moves values(328, 'Sand Tomb', 'Physical', 35, 85, 'Ground')
insert into moves values(329, 'Sheer Cold', 'Special', NULL, NULL, 'Ice')
insert into moves values(330, 'Muddy Water', 'Special', 90, 85, 'Water')
insert into moves values(331, 'Bullet Seed', 'Physical', 25, 100, 'Grass')
insert into moves values(332, 'Aerial Ace', 'Physical', 60, NULL, 'Flying')
insert into moves values(333, 'Icicle Spear', 'Physical', 25, 100, 'Ice')
insert into moves values(334, 'Iron Defense', 'Status', NULL, NULL, 'Steel')
insert into moves values(335, 'Block', 'Status', NULL, 100, 'Normal')
insert into moves values(336, 'Howl', 'Status', NULL, NULL, 'Normal')
insert into moves values(337, 'Dragon Claw', 'Physical', 80, 100, 'Dragon')
insert into moves values(338, 'Frenzy Plant', 'Special', 150, 90, 'Grass')
insert into moves values(339, 'Bulk Up', 'Status', NULL, NULL, 'Fighting')
insert into moves values(340, 'Bounce', 'Physical', 85, 85, 'Flying')
insert into moves values(341, 'Mud Shot', 'Special', 55, 95, 'Ground')
insert into moves values(342, 'Poison Tail', 'Physical', 50, 100, 'Poison')
insert into moves values(343, 'Covet', 'Physical', 60, 100, 'Normal')
insert into moves values(344, 'Volt Tackle', 'Physical', 120, 100, 'Electric')
insert into moves values(345, 'Magical Leaf', 'Special', 60, NULL, 'Grass')
insert into moves values(346, 'Water Sport', 'Status', NULL, 100, 'Water')
insert into moves values(347, 'Calm Mind', 'Status', NULL, NULL, 'Psychic')
insert into moves values(348, 'Leaf Blade', 'Physical', 90, 100, 'Grass')
insert into moves values(349, 'Dragon Dance', 'Status', NULL, NULL, 'Dragon')
insert into moves values(350, 'Rock Blast', 'Physical', 25, 90, 'Rock')
insert into moves values(351, 'Shock Wave', 'Special', 60, NULL, 'Electric')
insert into moves values(352, 'Water Pulse', 'Special', 60, 100, 'Water')
insert into moves values(353, 'Doom Desire', 'Special', 140, 100, 'Steel')
insert into moves values(354, 'Psycho Boost', 'Special', 140, 90, 'Psychic')
insert into moves values(355, 'Roost', 'Status', NULL, NULL, 'Flying')
insert into moves values(356, 'Gravity', 'Status', NULL, NULL, 'Psychic')
insert into moves values(357, 'Miracle Eye', 'Status', NULL, NULL, 'Psychic')
insert into moves values(358, 'Wake-Up Slap', 'Physical', 70, 100, 'Fighting')
insert into moves values(359, 'Hammer Arm', 'Physical', 100, 90, 'Fighting')
insert into moves values(360, 'Gyro Ball', 'Physical', NULL, 100, 'Steel')
insert into moves values(361, 'Healing Wish', 'Status', NULL, NULL, 'Psychic')
insert into moves values(362, 'Brine', 'Special', 65, 100, 'Water')
insert into moves values(363, 'Natural Gift', 'Physical', NULL, 100, 'Normal')
insert into moves values(364, 'Feint', 'Physical', 30, 100, 'Normal')
insert into moves values(365, 'Pluck', 'Physical', 60, 100, 'Flying')
insert into moves values(366, 'Tailwind', 'Status', NULL, NULL, 'Flying')
insert into moves values(367, 'Acupressure', 'Status', NULL, NULL, 'Normal')
insert into moves values(368, 'Metal Burst', 'Physical', NULL, 100, 'Steel')
insert into moves values(369, 'U-turn', 'Physical', 70, 100, 'Bug')
insert into moves values(370, 'Close Combat', 'Physical', 120, 100, 'Fighting')
insert into moves values(371, 'Payback', 'Physical', 50, 100, 'Dark')
insert into moves values(372, 'Assurance', 'Physical', 60, 100, 'Dark')
insert into moves values(373, 'Embargo', 'Status', NULL, 100, 'Dark')
insert into moves values(374, 'Fling', 'Physical', NULL, 100, 'Dark')
insert into moves values(375, 'Psycho Shift', 'Status', NULL, 100, 'Psychic')
insert into moves values(376, 'Trump Card', 'Special', NULL, NULL, 'Normal')
insert into moves values(377, 'Heal Block', 'Status', NULL, 100, 'Psychic')
insert into moves values(378, 'Wring Out', 'Special', NULL, 100, 'Normal')
insert into moves values(379, 'Power Trick', 'Status', NULL, NULL, 'Psychic')
insert into moves values(380, 'Gastro Acid', 'Status', NULL, 100, 'Poison')
insert into moves values(381, 'Lucky Chant', 'Status', NULL, NULL, 'Normal')
insert into moves values(382, 'Me First', 'Status', NULL, NULL, 'Normal')
insert into moves values(383, 'Copycat', 'Status', NULL, NULL, 'Normal')
insert into moves values(384, 'Power Swap', 'Status', NULL, NULL, 'Psychic')
insert into moves values(385, 'Guard Swap', 'Status', NULL, NULL, 'Psychic')
insert into moves values(386, 'Punishment', 'Physical', NULL, 100, 'Dark')
insert into moves values(387, 'Last Resort', 'Physical', 140, 100, 'Normal')
insert into moves values(388, 'Worry Seed', 'Status', NULL, 100, 'Grass')
insert into moves values(389, 'Sucker Punch', 'Physical', 80, 100, 'Dark')
insert into moves values(390, 'Toxic Spikes', 'Status', NULL, NULL, 'Poison')
insert into moves values(391, 'Heart Swap', 'Status', NULL, NULL, 'Psychic')
insert into moves values(392, 'Aqua Ring', 'Status', NULL, NULL, 'Water')
insert into moves values(393, 'Magnet Rise', 'Status', NULL, NULL, 'Electric')
insert into moves values(394, 'Flare Blitz', 'Physical', 120, 100, 'Fire')
insert into moves values(395, 'Force Palm', 'Physical', 60, 100, 'Fighting')
insert into moves values(396, 'Aura Sphere', 'Special', 80, NULL, 'Fighting')
insert into moves values(397, 'Rock Polish', 'Status', NULL, NULL, 'Rock')
insert into moves values(398, 'Poison Jab', 'Physical', 80, 100, 'Poison')
insert into moves values(399, 'Dark Pulse', 'Special', 80, 100, 'Dark')
insert into moves values(400, 'Night Slash', 'Physical', 70, 100, 'Dark')
insert into moves values(401, 'Aqua Tail', 'Physical', 90, 90, 'Water')
insert into moves values(402, 'Seed Bomb', 'Physical', 80, 100, 'Grass')
insert into moves values(403, 'Air Slash', 'Special', 75, 95, 'Flying')
insert into moves values(404, 'X-Scissor', 'Physical', 80, 100, 'Bug')
insert into moves values(405, 'Bug Buzz', 'Special', 90, 100, 'Bug')
insert into moves values(406, 'Dragon Pulse', 'Special', 85, 100, 'Dragon')
insert into moves values(407, 'Dragon Rush', 'Physical', 100, 75, 'Dragon')
insert into moves values(408, 'Power Gem', 'Special', 80, 100, 'Rock')
insert into moves values(409, 'Drain Punch', 'Physical', 75, 100, 'Fighting')
insert into moves values(410, 'Vacuum Wave', 'Special', 40, 100, 'Fighting')
insert into moves values(411, 'Focus Blast', 'Special', 120, 70, 'Fighting')
insert into moves values(412, 'Energy Ball', 'Special', 90, 100, 'Grass')
insert into moves values(413, 'Brave Bird', 'Physical', 120, 100, 'Flying')
insert into moves values(414, 'Earth Power', 'Special', 90, 100, 'Ground')
insert into moves values(415, 'Switcheroo', 'Status', NULL, 100, 'Dark')
insert into moves values(416, 'Giga Impact', 'Physical', 150, 90, 'Normal')
insert into moves values(417, 'Nasty Plot', 'Status', NULL, NULL, 'Dark')
insert into moves values(418, 'Bullet Punch', 'Physical', 40, 100, 'Steel')
insert into moves values(419, 'Avalanche', 'Physical', 60, 100, 'Ice')
insert into moves values(420, 'Ice Shard', 'Physical', 40, 100, 'Ice')
insert into moves values(421, 'Shadow Claw', 'Physical', 70, 100, 'Ghost')
insert into moves values(422, 'Thunder Fang', 'Physical', 65, 95, 'Electric')
insert into moves values(423, 'Ice Fang', 'Physical', 65, 95, 'Ice')
insert into moves values(424, 'Fire Fang', 'Physical', 65, 95, 'Fire')
insert into moves values(425, 'Shadow Sneak', 'Physical', 40, 100, 'Ghost')
insert into moves values(426, 'Mud Bomb', 'Special', 65, 85, 'Ground')
insert into moves values(427, 'Psycho Cut', 'Physical', 70, 100, 'Psychic')
insert into moves values(428, 'Zen Headbutt', 'Physical', 80, 90, 'Psychic')
insert into moves values(429, 'Mirror Shot', 'Special', 65, 85, 'Steel')
insert into moves values(430, 'Flash Cannon', 'Special', 80, 100, 'Steel')
insert into moves values(431, 'Rock Climb', 'Physical', 90, 85, 'Normal')
insert into moves values(432, 'Defog', 'Status', NULL, NULL, 'Flying')
insert into moves values(433, 'Trick Room', 'Status', NULL, NULL, 'Psychic')
insert into moves values(434, 'Draco Meteor', 'Special', 130, 90, 'Dragon')
insert into moves values(435, 'Discharge', 'Special', 80, 100, 'Electric')
insert into moves values(436, 'Lava Plume', 'Special', 80, 100, 'Fire')
insert into moves values(437, 'Leaf Storm', 'Special', 130, 90, 'Grass')
insert into moves values(438, 'Power Whip', 'Physical', 120, 85, 'Grass')
insert into moves values(439, 'Rock Wrecker', 'Physical', 150, 90, 'Rock')
insert into moves values(440, 'Cross Poison', 'Physical', 70, 100, 'Poison')
insert into moves values(441, 'Gunk Shot', 'Physical', 120, 80, 'Poison')
insert into moves values(442, 'Iron Head', 'Physical', 80, 100, 'Steel')
insert into moves values(443, 'Magnet Bomb', 'Physical', 60, NULL, 'Steel')
insert into moves values(444, 'Stone Edge', 'Physical', 100, 80, 'Rock')
insert into moves values(445, 'Captivate', 'Status', NULL, 100, 'Normal')
insert into moves values(446, 'Stealth Rock', 'Status', NULL, NULL, 'Rock')
insert into moves values(447, 'Grass Knot', 'Special', NULL, 100, 'Grass')
insert into moves values(448, 'Chatter', 'Special', 65, 100, 'Flying')
insert into moves values(449, 'Judgment', 'Special', 100, 100, 'Normal')
insert into moves values(450, 'Bug Bite', 'Physical', 60, 100, 'Bug')
insert into moves values(451, 'Charge Beam', 'Special', 50, 90, 'Electric')
insert into moves values(452, 'Wood Hammer', 'Physical', 120, 100, 'Grass')
insert into moves values(453, 'Aqua Jet', 'Physical', 40, 100, 'Water')
insert into moves values(454, 'Attack Order', 'Physical', 90, 100, 'Bug')
insert into moves values(455, 'Defend Order', 'Status', NULL, NULL, 'Bug')
insert into moves values(456, 'Heal Order', 'Status', NULL, NULL, 'Bug')
insert into moves values(457, 'Head Smash', 'Physical', 150, 80, 'Rock')
insert into moves values(458, 'Double Hit', 'Physical', 35, 90, 'Normal')
insert into moves values(459, 'Roar of Time', 'Special', 5, 15, 'Dragon')
insert into moves values(460, 'Spacial Rend', 'Special', 100, 95, 'Dragon')
insert into moves values(461, 'Lunar Dance', 'Status', NULL, NULL, 'Psychic')
insert into moves values(462, 'Crush Grip', 'Physical', NULL, 100, 'Normal')
insert into moves values(463, 'Magma Storm', 'Special', 100, 75, 'Fire')
insert into moves values(464, 'Dark Void', 'Status', NULL, 80, 'Dark')
insert into moves values(465, 'Seed Flare', 'Special', 120, 85, 'Grass')
insert into moves values(466, 'Ominous Wind', 'Special', 60, 100, 'Ghost')
insert into moves values(467, 'Shadow Force', 'Physical', 120, 100, 'Ghost')
insert into moves values(468, 'Hone Claws', 'Status', NULL, NULL, 'Dark')
insert into moves values(469, 'Wide Guard', 'Status', NULL, NULL, 'Rock')
insert into moves values(470, 'Guard Split', 'Status', NULL, NULL, 'Psychic')
insert into moves values(471, 'Power Split', 'Status', NULL, NULL, 'Psychic')
insert into moves values(472, 'Wonder Room', 'Status', NULL, NULL, 'Psychic')
insert into moves values(473, 'Psyshock', 'Special', 80, 100, 'Psychic')
insert into moves values(474, 'Venoshock', 'Special', 65, 100, 'Poison')
insert into moves values(475, 'Autotomize', 'Status', NULL, NULL, 'Steel')
insert into moves values(476, 'Rage Powder', 'Status', NULL, NULL, 'Bug')
insert into moves values(477, 'Telekinesis', 'Status', NULL, NULL, 'Psychic')
insert into moves values(478, 'Magic Room', 'Status', NULL, NULL, 'Psychic')
insert into moves values(479, 'Smack Down', 'Physical', 50, 100, 'Rock')
insert into moves values(480, 'Storm Throw', 'Physical', 60, 100, 'Fighting')
insert into moves values(481, 'Flame Burst', 'Special', 70, 100, 'Fire')
insert into moves values(482, 'Sludge Wave', 'Special', 95, 100, 'Poison')
insert into moves values(483, 'Quiver Dance', 'Status', NULL, NULL, 'Bug')
insert into moves values(484, 'Heavy Slam', 'Physical', NULL, 100, 'Steel')
insert into moves values(485, 'Synchronoise', 'Special', 120, 100, 'Psychic')
insert into moves values(486, 'Electro Ball', 'Special', NULL, 100, 'Electric')
insert into moves values(487, 'Soak', 'Status', NULL, 100, 'Water')
insert into moves values(488, 'Flame Charge', 'Physical', 50, 100, 'Fire')
insert into moves values(489, 'Coil', 'Status', NULL, NULL, 'Poison')
insert into moves values(490, 'Low Sweep', 'Physical', 65, 100, 'Fighting')
insert into moves values(491, 'Acid Spray', 'Special', 40, 100, 'Poison')
insert into moves values(492, 'Foul Play', 'Physical', 95, 100, 'Dark')
insert into moves values(493, 'Simple Beam', 'Status', NULL, 100, 'Normal')
insert into moves values(494, 'Entrainment', 'Status', NULL, 100, 'Normal')
insert into moves values(495, 'After You', 'Status', NULL, NULL, 'Normal')
insert into moves values(496, 'Round', 'Special', 60, 100, 'Normal')
insert into moves values(497, 'Echoed Voice', 'Special', 40, 100, 'Normal')
insert into moves values(498, 'Chip Away', 'Physical', 70, 100, 'Normal')
insert into moves values(499, 'Clear Smog', 'Special', 50, NULL, 'Poison')
insert into moves values(500, 'Stored Power', 'Special', 20, 100, 'Psychic')
insert into moves values(501, 'Quick Guard', 'Status', NULL, NULL, 'Fighting')
insert into moves values(502, 'Ally Switch', 'Status', NULL, NULL, 'Psychic')
insert into moves values(503, 'Scald', 'Special', 80, 100, 'Water')
insert into moves values(504, 'Shell Smash', 'Status', NULL, NULL, 'Normal')
insert into moves values(505, 'Heal Pulse', 'Status', NULL, NULL, 'Psychic')
insert into moves values(506, 'Hex', 'Special', 65, 100, 'Ghost')
insert into moves values(507, 'Sky Drop', 'Physical', 60, 100, 'Flying')
insert into moves values(508, 'Shift Gear', 'Status', NULL, NULL, 'Steel')
insert into moves values(509, 'Circle Throw', 'Physical', 60, 90, 'Fighting')
insert into moves values(510, 'Incinerate', 'Special', 60, 100, 'Fire')
insert into moves values(511, 'Quash', 'Status', NULL, 100, 'Dark')
insert into moves values(512, 'Acrobatics', 'Physical', 55, 100, 'Flying')
insert into moves values(513, 'Reflect Type', 'Status', NULL, NULL, 'Normal')
insert into moves values(514, 'Retaliate', 'Physical', 70, 100, 'Normal')
insert into moves values(515, 'Final Gambit', 'Special', NULL, 100, 'Fighting')
insert into moves values(516, 'Bestow', 'Status', NULL, NULL, 'Normal')
insert into moves values(517, 'Inferno', 'Special', 100, 50, 'Fire')
insert into moves values(518, 'Water Pledge', 'Special', 80, 100, 'Water')
insert into moves values(519, 'Fire Pledge', 'Special', 80, 100, 'Fire')
insert into moves values(520, 'Grass Pledge', 'Special', 80, 100, 'Grass')
insert into moves values(521, 'Volt Switch', 'Special', 70, 100, 'Electric')
insert into moves values(522, 'Struggle Bug', 'Special', 50, 100, 'Bug')
insert into moves values(523, 'Bulldoze', 'Physical', 60, 100, 'Ground')
insert into moves values(524, 'Frost Breath', 'Special', 60, 90, 'Ice')
insert into moves values(525, 'Dragon Tail', 'Physical', 60, 90, 'Dragon')
insert into moves values(526, 'Work Up', 'Status', NULL, NULL, 'Normal')
insert into moves values(527, 'Electroweb', 'Special', 55, 95, 'Electric')
insert into moves values(528, 'Wild Charge', 'Physical', 90, 100, 'Electric')
insert into moves values(529, 'Drill Run', 'Physical', 80, 95, 'Ground')
insert into moves values(530, 'Dual Chop', 'Physical', 40, 90, 'Dragon')
insert into moves values(531, 'Heart Stamp', 'Physical', 60, 100, 'Psychic')
insert into moves values(532, 'Horn Leech', 'Physical', 75, 100, 'Grass')
insert into moves values(533, 'Sacred Sword', 'Physical', 90, 100, 'Fighting')
insert into moves values(534, 'Razor Shell', 'Physical', 75, 95, 'Water')
insert into moves values(535, 'Heat Crash', 'Physical', NULL, 100, 'Fire')
insert into moves values(536, 'Leaf Tornado', 'Special', 65, 90, 'Grass')
insert into moves values(537, 'Steamroller', 'Physical', 65, 100, 'Bug')
insert into moves values(538, 'Cotton Guard', 'Status', NULL, NULL, 'Grass')
insert into moves values(539, 'Night Daze', 'Special', 85, 95, 'Dark')
insert into moves values(540, 'Psystrike', 'Special', 100, 100, 'Psychic')
insert into moves values(541, 'Tail Slap', 'Physical', 25, 85, 'Normal')
insert into moves values(542, 'Hurricane', 'Special', 110, 70, 'Flying')
insert into moves values(543, 'Head Charge', 'Physical', 120, 100, 'Normal')
insert into moves values(544, 'Gear Grind', 'Physical', 50, 85, 'Steel')
insert into moves values(545, 'Searing Shot', 'Special', 100, 100, 'Fire')
insert into moves values(546, 'Techno Blast', 'Special', 120, 100, 'Normal')
insert into moves values(547, 'Relic Song', 'Special', 75, 100, 'Normal')
insert into moves values(548, 'Secret Sword', 'Special', 85, 100, 'Fighting')
insert into moves values(549, 'Glaciate', 'Special', 65, 95, 'Ice')
insert into moves values(550, 'Bolt Strike', 'Physical', 130, 85, 'Electric')
insert into moves values(551, 'Blue Flare', 'Special', 130, 85, 'Fire')
insert into moves values(552, 'Fiery Dance', 'Special', 80, 100, 'Fire')
insert into moves values(553, 'Freeze Shock', 'Physical', 140, 90, 'Ice')
insert into moves values(554, 'Ice Burn', 'Special', 140, 90, 'Ice')
insert into moves values(555, 'Snarl', 'Special', 55, 95, 'Dark')
insert into moves values(556, 'Icicle Crash', 'Physical', 85, 90, 'Ice')
insert into moves values(557, 'V-create', 'Physical', 180, 95, 'Fire')
insert into moves values(558, 'Fusion Flare', 'Special', 100, 100, 'Fire')
insert into moves values(559, 'Fusion Bolt', 'Physical', 100, 100, 'Electric')
insert into moves values(560, 'Flying Press', 'Physical', 80, 95, 'Fighting')
insert into moves values(561, 'Mat Block', 'Status', NULL, NULL, 'Fighting')
insert into moves values(562, 'Belch', 'Special', 120, 90, 'Poison')
insert into moves values(563, 'Rototiller', 'Status', NULL, NULL, 'Ground')
insert into moves values(564, 'Sticky Web', 'Status', NULL, NULL, 'Bug')
insert into moves values(565, 'Fell Stinger', 'Physical', 30, 100, 'Bug')
insert into moves values(566, 'Phantom Force', 'Physical', 90, 100, 'Ghost')
insert into moves values(567, 'Trick-or-Treat', 'Status', NULL, 100, 'Ghost')
insert into moves values(568, 'Noble Roar', 'Status', NULL, 100, 'Normal')
insert into moves values(569, 'Ion Deluge', 'Status', NULL, NULL, 'Electric')
insert into moves values(570, 'Parabolic Charge', 'Special', 50, 100, 'Electric')
insert into moves values(571, 'Forests Curse', 'Status', NULL, 100, 'Grass')
insert into moves values(572, 'Petal Blizzard', 'Physical', 90, 100, 'Grass')
insert into moves values(573, 'Freeze-Dry', 'Special', 70, 100, 'Ice')
insert into moves values(574, 'Disarming Voice', 'Special', 40, NULL, 'Fairy')
insert into moves values(575, 'Parting Shot', 'Status', NULL, 100, 'Dark')
insert into moves values(576, 'Topsy-Turvy', 'Status', NULL, 100, 'Dark')
insert into moves values(577, 'Draining Kiss', 'Special', 50, 100, 'Fairy')
insert into moves values(578, 'Crafty Shield', 'Status', NULL, NULL, 'Fairy')
insert into moves values(579, 'Flower Shield', 'Status', NULL, NULL, 'Fairy')
insert into moves values(580, 'Grassy Terrain', 'Status', NULL, NULL, 'Grass')
insert into moves values(581, 'Misty Terrain', 'Status', NULL, NULL, 'Fairy')
insert into moves values(582, 'Electrify', 'Status', NULL, NULL, 'Electric')
insert into moves values(583, 'Play Rough', 'Physical', 90, 90, 'Fairy')
insert into moves values(584, 'Fairy Wind', 'Special', 40, NULL, 'Fairy')
insert into moves values(585, 'Moonblast', 'Special', 95, 100, 'Fairy')
insert into moves values(586, 'Boomburst', 'Special', 140, 100, 'Normal')
insert into moves values(587, 'Fairy Lock', 'Status', NULL, NULL, 'Fairy')
insert into moves values(588, 'Kings Shield', 'Status', NULL, NULL, 'Steel')
insert into moves values(589, 'Play Nice', 'Status', NULL, NULL, 'Normal')
insert into moves values(590, 'Confide', 'Status', NULL, NULL, 'Normal')
insert into moves values(591, 'Diamond Storm', 'Physical', 100, 95, 'Rock')
insert into moves values(594, 'Water Shuriken', 'Physical', 15, 100, 'Water')
insert into moves values(595, 'Mystical Fire', 'Special', 65, 100, 'Fire')
insert into moves values(596, 'Spiky Shield', 'Status', NULL, NULL, 'Grass')
insert into moves values(597, 'Aromatic Mist', 'Status', NULL, NULL, 'Fairy')
insert into moves values(598, 'Eerie Impulse', 'Status', NULL, 100, 'Electric')
insert into moves values(599, 'Venom Drench', 'Status', NULL, 100, 'Poison')
insert into moves values(600, 'Powder', 'Status', NULL, 100, 'Bug')
insert into moves values(601, 'Geomancy', 'Status', NULL, NULL, 'Fairy')
insert into moves values(602, 'Magnetic Flux', 'Status', NULL, NULL, 'Electric')
insert into moves values(603, 'Happy Hour', 'Status', NULL, NULL, 'Normal')
insert into moves values(604, 'Electric Terrain', 'Status', NULL, NULL, 'Electric')
insert into moves values(605, 'Dazzling Gleam', 'Special', 80, 100, 'Fairy')
insert into moves values(606, 'Celebrate', 'Status', NULL, NULL, 'Normal')
insert into moves values(607, '???', '???', ???, ??, '???')
insert into moves values(608, 'Baby-Doll Eyes', 'Status', NULL, 100, 'Fairy')
insert into moves values(609, 'Nuzzle', 'Physical', 20, 100, 'Electric')
insert into moves values(610, 'Hold Back', 'Physical', 40, 100, 'Normal')
insert into moves values(611, 'Infestation', 'Special', 20, 100, 'Bug')
insert into moves values(612, 'Power-Up Punch', 'Physical', 40, 100, 'Fighting')
insert into moves values(613, 'Oblivion Wing', 'Special', 80, 100, 'Flying')
insert into moves values(616, 'Lands Wrath', 'Physical', 90, 100, 'Ground')
